Camera control
AMIOL7/ELME pull request #16
Opened 2022-10-23 15:16 UTC by AMIOL7

Here is my implementation of camera control. Please review it

2022-10-23 15:18 UTC, vismate commented on app/src/main/java/ELME/App.java
> +//        cam.setClampToMap(true);
Maybe remove comments?

2022-10-23 15:19 UTC, vismate commented on app/src/main/java/View/CustomWheelListener.java
> + * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
Remove license template

2022-10-23 15:20 UTC, vismate commented on app/src/main/java/View/CustomWheelListener.java
> +    private Camera cam;
Camera does not need to be stored. ```Game.world.camera()``` can get you the current camera.

2022-10-23 15:23 UTC, vismate requested changes

2022-10-23 15:23 UTC, vismate commented on app/src/main/java/View/MainScreen.java
> +        BufferedImage img = null;
I recommend not opening an image at all, because we don't have any images stored in the repo. Also this code opens the image EVERY FRAME!

2022-10-23 15:23 UTC, vismate commented on app/src/main/java/View/MouseDraggedListener.java
> +        System.out.println("Dragging: "+dragging);
Debug prints should be removed.

2022-10-23 15:25 UTC, AMIOL7 commented
Your comments are received will work on them a bit later

2022-10-25 18:45 UTC, AMIOL7 commented
@vismate Your comments have been resolved. Please review again

2022-10-25 18:47 UTC, AMIOL7 commented
Changes based on @vismate's comments have been made. Please review again

2022-10-25 18:53 UTC, vismate commented on app/src/main/java/ELME/App.java
>   */
This comment could be removed

2022-10-25 18:53 UTC, vismate commented on app/src/main/java/ELME/App.java
> +        System.out.println("Camera printout: "+cam.getZoom());
Debug prints could be removed.

2022-10-25 18:53 UTC, vismate commented on app/src/main/java/ELME/View/CustomWheelListener.java
> +//        cam.update();
Comment could be removed

2022-10-25 18:53 UTC, vismate commented on app/src/main/java/ELME/View/MainScreen.java
> + * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
License template could be removed

2022-10-25 18:53 UTC, vismate commented on app/src/main/java/ELME/View/MouseDraggedListener.java
> + * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
License template could be removed

2022-10-25 18:53 UTC, vismate commented on app/src/main/java/ELME/View/CustomWheelListener.java
> +        this.cam = Game.world().camera();
If camera changes after construction, the zoom functionality would not work. I recommend not storing a reference to a camera all together. Game.world().camera() could be used in method t set zoom.

2022-10-25 18:53 UTC, vismate approved these changes

2022-10-25 18:56 UTC, vismate commented
About my latest comments: I admit, I am a bit nit-picky. I do apologize, I don't want to block progress, so we can merge regardless.  I could also make these changes myself, if you feel like it.

2022-10-25 19:00 UTC, AMIOL7 commented
@vismate Already done myself.

2022-10-25 19:01 UTC, AMIOL7 commented
@pszi and @bgdxqi Please review this pull request

2022-10-25 19:01 UTC, vismate commented
> @vismate Already done myself.

Fantastic! Thank you!

2022-10-25 19:03 UTC, vismate commented
Would you like to merge now, or we should wait for other reviews?

2022-10-25 19:04 UTC, AMIOL7 commented
I'd wait for at least 1 more review, but if it can't wait  we can merge now

2022-10-25 19:19 UTC, vismate commented
I'd like to start working on things that requires this branch. But I agree, one more person should review it at least. @pszi @bgdxqi Could one of you review it tomorrow, please?

2022-10-26 21:20 UTC, bgdxqi approved these changes
I might be not the most fit to review this. But to me it looks fine :D

2022-10-26 21:58 UTC, vismate commented
Then this branch should be merged, in my oppinion.

2022-10-27 05:50 UTC, AMIOL7 commented
I am merging it now

2022-10-27 05:51 UTC, merged