View/UI
AMIOL7/ELME pull request #20
Opened 2022-10-31 19:23 UTC by pszi

Since the source packages have been restructured recently, I'm not sure that the files could be transited into their right places, can you please help with that? Also, I don't mind if the merge is postponed, but perhaps it would be a good idea if every new branch could come off of main from now on.

2022-11-01 22:35 UTC, vismate commented
I mean we could do a manual merge, but I think it would be way easier for now if you just made the same restucturing we did on main. (Resolving conflicts manually would be essentially the same.) After that, we'll test an review the code. 😁

2022-11-02 18:19 UTC, vismate commented
Just looked at the code, looks good. I'll build and test it in a few hours. It has conflicts with the camera control branch already merged into main, so we'll need to resolve the conflicts. I propose we all review the code and make necessary changes this week. At our weekly meeting we could go over it together to resolve the conflicts.

2022-11-02 18:38 UTC, pszi commented
The the source of that conflict is simply that I've changed it so that dragging the mouse would only spam the coordinate values in the console when the right button is being pressed, because it interfered with my manual testing of the menu buttons. It was literally moving one if-condition.
How does reviewing these conflicts work? Is it just the work of one person, or do we need a consensus? I don't want to accidentally remove someone else's code.

2022-11-05 16:51 UTC, vismate requested changes

2022-11-05 16:51 UTC, vismate commented on app/src/main/java/ELME/View/Toolbar.java
> +package View;
Incorrect package. Should be ELME.View

2022-11-05 16:51 UTC, vismate commented on app/src/main/java/ELME/View/SideMenu.java
> +package View;
Incorrect package

2022-11-05 16:51 UTC, vismate commented on app/src/main/java/ELME/View/SideMenu.java
> +import java.util.List;
Unused imports from here on

2022-11-05 16:51 UTC, vismate commented on app/src/main/java/ELME/View/SideMenu.java
> +    //private final List<Consumer<Integer>> confirmConsumer;
Commented lines could be removed.

2022-11-05 16:51 UTC, vismate commented on app/src/main/java/ELME/View/ExtraMenu.java
> +package View;
Incorrect package

2022-11-05 17:50 UTC, vismate approved these changes

2022-11-05 18:00 UTC, merged